name: news_application_2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  http: ^1.2.1
  cached_network_image: ^3.3.1
  intl: ^0.19.0 
  # fluttertoast: ^8.2.6
  firebase_database: ^11.0.3
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  flutter_dotenv: ^5.1.0
  another_flushbar: ^1.12.30
  adaptive_theme: ^3.6.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  # get: ^4.6.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0



# The following section is specific to Flutter packages.
flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/.env



